In [1]:
import pandas as pd

In [14]:
data_50 = pd.read_csv('data_50_new.csv')

data_50 = pd.get_dummies(data_50, columns= ['RSF'])

data_50['date'] = pd.to_datetime(data_50['date'])

data_50['next_date'] = data_50['date'].shift(-1)

data_50['day_diff'] = data_50.next_date - data_50.date 

In [16]:
data_50[data_50.day_diff== '1 days']

Unnamed: 0  station_no       date  discharge  water_level  incoming  \
0          833952     6335050 1965-01-01    1320.00          219  1358.890   
1          833953     6335050 1965-01-02    1650.00          272  1814.940   
2          833954     6335050 1965-01-03    1950.00          315  1939.090   
3          833955     6335050 1965-01-04    1870.00          304  1885.800   
4          833956     6335050 1965-01-05    1870.00          304  1877.250   
5          833957     6335050 1965-01-06    1770.00          290  1696.740   
6          833958     6335050 1965-01-07    1650.00          272  1640.250   
7          833959     6335050 1965-01-08    1650.00          272  1707.580   
8          833960     6335050 1965-01-09    1830.00          299  2115.920   
9          833961     6335050 1965-01-10    2350.00          370  2904.000   
10         833962     6335050 1965-01-11    3340.00          484  3992.380   
11         833963     6335050 1965-01-12    4080.00          556  4277.800   
12         833964     6335050 1965-01-13    3900.00          539  3781.640   
13         833965     6335050 1965-01-14    3310.00          481  3136.300   
14         833966     6335050 1965-01-15    2810.00          426  2722.160   
15         833967     6335050 1965-01-16    2510.00          390  2509.460   
16         833968     6335050 1965-01-17    2390.00          375  2475.850   
17         833969     6335050 1965-01-18    2670.00          410  3117.070   
18         833970     6335050 1965-01-19    3830.00          533  4151.870   
19         833971     6335050 1965-01-20    4080.00          556  4086.920   
20         833972     6335050 1965-01-21    4000.00          549  3921.470   
21         833973     6335050 1965-01-22    3510.00          501  3351.790   
22         833974     6335050 1965-01-23    3000.00          448  2874.380   
23         833975     6335050 1965-01-24    2630.00          405  2569.480   
24         833976     6335050 1965-01-25    2440.00          382  2445.100   
25         833977     6335050 1965-01-26    2380.00          374  2393.970   
26         833978     6335050 1965-01-27    2330.00          368  2300.720   
27         833979     6335050 1965-01-28    2270.00          359  2248.710   
28         833980     6335050 1965-01-29    2220.00          353  2171.440   
29         833981     6335050 1965-01-30    2080.00          334  2060.230   
...           ...         ...        ...        ...          ...       ...   
14860      848812     6335050 2012-11-14    2710.19          365  2771.384   
14861      848813     6335050 2012-11-15    2756.92          371  2756.930   
14862      848814     6335050 2012-11-16    2638.96          356  2593.476   
14863      848815     6335050 2012-11-17    2459.41          333  2408.016   
14864      848816     6335050 2012-11-18    2290.67          310  2241.561   
14866      848818     6335050 2012-12-06    2183.77          296  2297.739   
14867      848819     6335050 2012-12-07    2494.27          337  2622.464   
14868      848820     6335050 2012-12-08    2636.49          356  2632.230   
14869      848821     6335050 2012-12-09    2478.49          335  2426.178   
14870      848822     6335050 2012-12-10    2359.18          320  2325.697   
14871      848823     6335050 2012-12-11    2243.79          304  2275.648   
14872      848824     6335050 2012-12-12    2218.35          301  2251.838   
14873      848825     6335050 2012-12-13    2162.74          293  2172.597   
14874      848826     6335050 2012-12-14    2050.93          277  2040.500   
14875      848827     6335050 2012-12-15    2003.00          271  2068.098   
14876      848828     6335050 2012-12-16    2410.28          326  2802.465   
14877      848829     6335050 2012-12-17    3456.68          453  3955.452   
14878      848830     6335050 2012-12-18    4429.66          556  4837.875   
14879      848831     6335050 2012-12-19    5032.05          615  5321.633   
14880      848832     6335050

In [23]:
data_60 = pd.read_csv('data_60_new.csv')

data_60 = pd.get_dummies(data_60, columns= ['RSF'])

data_60['date'] = pd.to_datetime(data_60['date'])

data_60['next_date'] = data_60['date'].shift(-1)

data_60['day_diff'] = data_60.next_date - data_60.date 

In [6]:
data_50 = pd.read_csv('data_50.csv')
data_50.head()

Unnamed: 0  station_no      date  discharge  water_level  incoming   RS  \
0           0     6335050  1/1/1965     1320.0          219   1358.89  1.2   
1           1     6335050  1/2/1965     1650.0          272   1814.94  0.3   
2           2     6335050  1/3/1965     1950.0          315   1939.09  0.1   
3           3     6335050  1/4/1965     1870.0          304   1885.80  0.0   
4           4     6335050  1/5/1965     1870.0          304   1877.25  1.2   

   SH_TAG  NSH_TAG  RSF_0.0  RSF_1.0  RSF_4.0  RSF_6.0  RSF_7.0  RSF_8.0  \
0     1.2      0.0        0        1        0        0        0        0   
1     0.3      0.0        0        1        0        0        0        0   
2     0.1      0.0        0        1        0        0        0        0   
3     0.0      0.0        0        0        0        0        1        0   
4     1.2      0.0        0        1        0        0        0        0   

  next_date                   day_diff  
0  1/2/1965  1 days 00:00:00.000000000  
1  1/3/1965  1 days 00:00:00.000000000  
2  1/4/1965  1 days 00:00:00.000000000  
3  1/5/1965  1 days 00:00:00.000000000  
4  1/6/1965  1 days 00:00:00.000000000

In [3]:
data_50.day_diff.unique()

array(['1 days 00:00:00.000000000', '17 days 00:00:00.000000000', nan],
      dtype=object)

In [8]:
data_50[data_50.day_diff == '1 days 00:00:00.000000000']

Unnamed: 0  station_no        date  discharge  water_level  incoming  \
0               0     6335050    1/1/1965    1320.00          219  1358.890   
1               1     6335050    1/2/1965    1650.00          272  1814.940   
2               2     6335050    1/3/1965    1950.00          315  1939.090   
3               3     6335050    1/4/1965    1870.00          304  1885.800   
4               4     6335050    1/5/1965    1870.00          304  1877.250   
5               5     6335050    1/6/1965    1770.00          290  1696.740   
6               6     6335050    1/7/1965    1650.00          272  1640.250   
7               7     6335050    1/8/1965    1650.00          272  1707.580   
8               8     6335050    1/9/1965    1830.00          299  2115.920   
9               9     6335050   1/10/1965    2350.00          370  2904.000   
10             10     6335050   1/11/1965    3340.00          484  3992.380   
11             11     6335050   1/12/1965    4080.00          556  4277.800   
12             12     6335050   1/13/1965    3900.00          539  3781.640   
13             13     6335050   1/14/1965    3310.00          481  3136.300   
14             14     6335050   1/15/1965    2810.00          426  2722.160   
15             15     6335050   1/16/1965    2510.00          390  2509.460   
16             16     6335050   1/17/1965    2390.00          375  2475.850   
17             17     6335050   1/18/1965    2670.00          410  3117.070   
18             18     6335050   1/19/1965    3830.00          533  4151.870   
19             19     6335050   1/20/1965    4080.00          556  4086.920   
20             20     6335050   1/21/1965    4000.00          549  3921.470   
21             21     6335050   1/22/1965    3510.00          501  3351.790   
22             22     6335050   1/23/1965    3000.00          448  2874.380   
23             23     6335050   1/24/1965    2630.00          405  2569.480   
24             24     6335050   1/25/1965    2440.00          382  2445.100   
25             25     6335050   1/26/1965    2380.00          374  2393.970   
26             26     6335050   1/27/1965    2330.00          368  2300.720   
27             27     6335050   1/28/1965    2270.00          359  2248.710   
28             28     6335050   1/29/1965    2220.00          353  2171.440   
29             29     6335050   1/30/1965    2080.00          334  2060.230   
...           ...         ...         ...        ...          ...       ...   
14860       14860     6335050  11/14/2012    2710.19          365  2771.384   
14861       14861     6335050  11/15/2012    2756.92          371  2756.930   
14862       14862     6335050  11/16/2012    2638.96          356  2593.476   
14863       14863     6335050  11/17/2012    2459.41          333  2408.016   
14864       14864     6335050  11/18/2012    2290.67          310  2241.561   
14866       14866     6335050   12/6/2012    2183.77          296  2297.739   
14867       14867     6335050   12/7/2012    2494.27          337  2622.464   
14868       14868     6335050   12/8/2012    2636.49          356  2632.230   
14869       14869     6335050   12/9/2012    2478.49          335  2426.178   
14870       14870     6335050  12/10/2012    2359.18          320  2325.697   
14871       14871     6335050  12/11/2012    2243.79          304  2275.648   
14872       14872     6335050  12/12/2012    2218.35          301  2251.838   
14873       14873     6335050  12/13/2012    2162.74          293  2172.597   
14874       14874     6335050  12/14/2012    2050.93          277  2040.500   
14875       14875     6335050  12/15/2012    2003.00          271  2068.098   
14876       14876     6335050  12/16/2012    2410.28          326  2802.465   
14877       14877     6335050  12/17/2012    3456.68          453  3955.452   
14878       14878     6335050  12/18/2012    4429.66          556  4837.875   
14879       14879     6335050  12/19/2012    5032.05     

In [10]:
data_50.iloc[0:10].values

array([[0, 6335050, '1/1/1965', 1320.0, 219, 1358.89, 1.2, 1.2, 0.0, 0,
        1, 0, 0, 0, 0, '1/2/1965', '1 days 00:00:00.000000000'],
       [1, 6335050, '1/2/1965', 1650.0, 272, 1814.94, 0.3, 0.3, 0.0, 0,
        1, 0, 0, 0, 0, '1/3/1965', '1 days 00:00:00.000000000'],
       [2, 6335050, '1/3/1965', 1950.0, 315, 1939.09, 0.1, 0.1, 0.0, 0,
        1, 0, 0, 0, 0, '1/4/1965', '1 days 00:00:00.000000000'],
       [3, 6335050, '1/4/1965', 1870.0, 304, 1885.8, 0.0, 0.0, 0.0, 0, 0,
        0, 0, 1, 0, '1/5/1965', '1 days 00:00:00.000000000'],
       [4, 6335050, '1/5/1965', 1870.0, 304, 1877.25, 1.2, 1.2, 0.0, 0,
        1, 0, 0, 0, 0, '1/6/1965', '1 days 00:00:00.000000000'],
       [5, 6335050, '1/6/1965', 1770.0, 290, 1696.74, 7.8, 7.8, 0.0, 0,
        1, 0, 0, 0, 0, '1/7/1965', '1 days 00:00:00.000000000'],
       [6, 6335050, '1/7/1965', 1650.0, 272, 1640.25, 14.9, 14.9, 0.0, 0,
        1, 0, 0, 0, 0, '1/8/1965', '1 days 00:00:00.000000000'],
       [7, 6335050, '1/8/1965', 1650.0, 

In [58]:
ts_cols = all_cols[:,3:-2]

ts_cols

array([[1320.0, 219, 1358.89, 1.2, 1.2, 0.0, 0, 1, 0, 0, 0, 0],
       [1650.0, 272, 1814.94, 0.3, 0.3, 0.0, 0, 1, 0, 0, 0, 0],
       [1950.0, 315, 1939.09, 0.1, 0.1, 0.0, 0, 1, 0, 0, 0, 0],
       [1870.0, 304, 1885.8, 0.0, 0.0, 0.0, 0, 0, 0, 0, 1, 0],
       [1870.0, 304, 1877.25, 1.2, 1.2, 0.0, 0, 1, 0, 0, 0, 0],
       [1770.0, 290, 1696.74, 7.8, 7.8, 0.0, 0, 1, 0, 0, 0, 0],
       [1650.0, 272, 1640.25, 14.9, 14.9, 0.0, 0, 1, 0, 0, 0, 0],
       [1650.0, 272, 1707.58, 9.8, 9.8, 0.0, 0, 1, 0, 0, 0, 0],
       [1830.0, 299, 2115.92, 8.2, 8.2, 0.0, 0, 1, 0, 0, 0, 0],
       [2350.0, 370, 2904.0, 7.1, 7.1, 0.0, 0, 1, 0, 0, 0, 0]],
      dtype=object)

In [16]:
predict_index = data_50[data_50.day_diff == '17 days 00:00:00.000000000'].index

In [81]:
# Univariate

data  = np.random.randn(10,2)

x_input = data[2:6, 0]

In [82]:
x_input = x_input.reshape((len(x_input), 1))
# X.append(x_input)
x_input

array([[ 1.25851599],
       [-1.76209204],
       [-1.08940638],
       [ 1.88407774]])

In [85]:
X = []
X.append(x_input)
X.append(x_input)


In [86]:
X

[array([[-0.2079455 , -1.46134552],
        [-1.91801769, -0.29176018],
        [-1.12937664,  0.03258345],
        [-2.00240361,  2.21019179]]), array([[-0.2079455 , -1.46134552],
        [-1.91801769, -0.29176018],
        [-1.12937664,  0.03258345],
        [-2.00240361,  2.21019179]])]

In [84]:
# Multivariate

data  = np.random.randn(10,2)

x_input = data[2:6, :]

x_input

array([[-0.2079455 , -1.46134552],
       [-1.91801769, -0.29176018],
       [-1.12937664,  0.03258345],
       [-2.00240361,  2.21019179]])

window = 3

In [31]:
import numpy as np

In [54]:
window = 3

def get_train_index(window):
    l = [] #np.array([])

    start = 0

    for indice in predict_index:
        last_1 = indice - window + 1

        lst = []

        for j in range(start, last_1):
            lst.append(j)

        l.append((lst))

        start = indice + 1


    flattened_list = [y for x in l for y in x]
    return flattened_list

In [59]:
data_50.iloc[0:2]

Unnamed: 0  station_no      date  discharge  water_level  incoming   RS  \
0           0     6335050  1/1/1965     1320.0          219   1358.89  1.2   
1           1     6335050  1/2/1965     1650.0          272   1814.94  0.3   

   SH_TAG  NSH_TAG  RSF_0.0  RSF_1.0  RSF_4.0  RSF_6.0  RSF_7.0  RSF_8.0  \
0     1.2      0.0        0        1        0        0        0        0   
1     0.3      0.0        0        1        0        0        0        0   

  next_date                   day_diff  
0  1/2/1965  1 days 00:00:00.000000000  
1  1/3/1965  1 days 00:00:00.000000000

In [101]:
data_cols = data_50.iloc[0: 0+window]
    

In [95]:
ts_cols = data_cols.iloc[:,3:-2]
ts_cols

discharge  water_level  incoming   RS  SH_TAG  NSH_TAG  RSF_0.0  RSF_1.0  \
0     1320.0          219   1358.89  1.2     1.2      0.0        0        1   
1     1650.0          272   1814.94  0.3     0.3      0.0        0        1   
2     1950.0          315   1939.09  0.1     0.1      0.0        0        1   

   RSF_4.0  RSF_6.0  RSF_7.0  RSF_8.0  
0        0        0        0        0  
1        0        0        0        0  
2        0        0        0        0

In [108]:
def predict_data(df, window, y_window, index):
    
    data_cols = df.iloc[index: index+window]
    
    ts_cols = data_cols.iloc[:,3:-2].values

    y_future = df.iloc[index+window: index+window+y_window, 4].values
    
    return ts_cols, y_future

In [109]:
x,y = predict_data(data_50, 15,13, 0)

In [112]:
x.shape

(15, 12)